### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by compflashing** [compflashing/usdt_flasher#1]
- [ ] Improve Transaction time 
- [ ] 2-4h > 15m-2h
- [ ] 
- [ ]  ~~Add Networks~~
- [ ] ~~TRX, BTC > BEP20, TRX, BTC, ERC20, MATIC, ETC..~~ RESOLVED: GOT ACCESS TO MULTICHAIN PROXY
- [ ] 
- [ ] Automatically clean flash usdt
- [ ]
